[features]
seeds = false
skip-lint = false
[programs.localnet]
crowdfunding = "95A2UHGSZtCFUjZk4k79qvMsM8yTJDM1w7ydVtjvTvPX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/maksim/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
